#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>
#include<fcntl.h>
#include<linux/input.h> // linux specific header provided by kernel headers

#define DEVICE_PATH "/dev/input/event0" // this path is created automatically by kernel driver
const char *LEDS[] = {
    "/sys/class/leds/beagle-x15:usr0/brightness",
    "/sys/class/leds/beagle-x15:usr1/brightness",
    "/sys/class/leds/beagle-x15:usr2/brightness",
    "/sys/class/leds/beagle-x15:usr3/brightness",
};

int main(void)
{
    // data structure to transfer input events (type, code, value) from kernel to user space
    struct input_event ev;

    int fd;

    // O_RDONLY: open device for reading events
    fd = open(DEVICE_PATH, O_RDONLY);

    if(fd < 0)
    {
        perror("Error opening input device");
        return 1;
    }

    printf("Listening for GPIO key events on %s...\n", DEVICE_PATH);

    while(1)
    {
        FILE *led = NULL;

        // read binary events generated by GPIO key drivers
        ssize_t n = read(fd, &ev, sizeof(ev));

        if(n == (ssize_t) - 1)
        {
            perror("Read Error");
            break;
        }

        if(n != sizeof(ev))
        {
            fprintf(stderr, "Unexpected event size\n");
            continue;
        }

        // ev.type: 0x01 standard linux input event, ev.code: identify th key number (256 for USER1), ev.value: sent by kernel on GPIO event (1: pressed, 0: value)
        if(ev.type == EV_KEY)
        {
            printf("Key event: code %d value %d (%s)\n", ev.code, ev.value, ev.value ? "PRESSED" : "RELEASED");
            fflush(stdout);
        }

        int led_num = -1;
        if(ev.code == 103) {
            led = fopen(LEDS[1], "w");
            led_num = 0;
        }

        else if(ev.code == 108) {
            led = fopen(LEDS[0], "w");
            led_num = 1;
        }

        else if(ev.code == 105) {
            led = fopen(LEDS[2], "w");
            led_num = 2;
        }

        else if(ev.code == 106 || ev.code == 102) {
            led = fopen(LEDS[3], "w");
            led_num = 3;
        }

        else {
            fprintf(stderr, "Unexpected event\n");
            continue;
        }

        if(led == NULL)
        {
            perror("Error opening led brightness file");
            return -1;
        }

        fprintf(led, "%d", ev.value);
        printf("LED %s turned %s\n", LEDS[led_num], ev.value ? "ON" : "OFF");
        fclose(led);
    }

    close(fd);
    return 0;
}
