#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>
#include<fcntl.h>
#include<linux/input.h> // linux specific header provided by kernel headers

#define DEVICE_PATH "/dev/input/event0" // this path is created automatically by kernel driver

int main(void)
{
    // data structure to transfer input events (type, code, value) from kernel to user space
    struct input_event ev;

    int fd;

    // O_RDONLY: open device for reading events
    fd = open(DEVICE_PATH, O_RDONLY);

    if(fd < 0)
    {
        perror("Error opening input device");
        return 1;
    }

    printf("Listening for GPIO key events on %s...\n", DEVICE_PATH);

    while(1)
    {
        // read binary events generated by GPIO key drivers
        ssize_t n = read(fd, &ev, sizeof(ev));

        if(n == (ssize_t) - 1)
        {
            perror("Read Error");
            break;
        }

        if(n != sizeof(ev))
        {
            fprintf(stderr, "Unexpected event size\n");
            continue;
        }

        // ev.type: 0x01 standard linux input event, ev.code: identify th key number (256 for USER1), ev.value: sent by kernel on GPIO event (1: pressed, 0: value)
        if(ev.type == EV_KEY)
        {
            printf("Key event: code %d value %d (%s)\n", ev.code, ev.value, ev.value ? "PRESSED" : "RELEASED");
            fflush(stdout);
        }
    }

    close(fd);
    return 0;
}
